calender/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
	url(r'^$',views.index,name='calender_index'),
	url(r'^addNewEvent$',views.newEvent,name='add_new_event'),
	url(r'^getEventsByMonth$',views.events_for_month,name='events_for_month'),

]

core/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm

urlpatterns = [
	url(r'^login/$',views.authorize,name='login'),
	url(r'^logout/$', auth_views.logout, {'next_page': '/accounts/login/'}, name='logout'),
	url(r'^signup$',views.signup,name='signup'),
	url(r'^dash/$',views.dash,name='dash'),
	url(r'^comingsoon$',views.comingsoon,name='cusoon')
]

gettingstarted/urls.py
from django.conf.urls import include, url
from django.contrib import admin
admin.autodiscover()

import landingpage.views

# Examples:
# url(r'^$', 'gettingstarted.views.home', name='home'),
# url(r'^blog/', include('blog.urls')),

urlpatterns = [
    url(r'^$', landingpage.views.index, name='index'),
    url(r'^accounts/',include('core.urls')),
    url(r'^calender/',include('calender.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

landingpage/urls.py
from django.conf.urls import url,include

from . import views

urlpatterns = [
	url(r'^$',views.index,name='landingpage_index')
]

calender/models.py
from django.db import models
from django.utils import timezone


class CalenderEvent(models.Model):     
    creator_name = models.CharField(max_length=40, default="Admin")
    event_level = models.CharField(max_length=10, default="General")
    event_name = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    start_date = models.CharField(max_length=50)
    start_time = models.CharField(max_length=50, default="")
    description = models.TextField(default="")
    completed = models.BooleanField(default=False)
    def __str__(self):
        return 'Event:{} On {}'.format(self.event_name,self.start_date)

core/models.py
from django.db import models

# Create your models here.

calender/forms.py
from django import forms
from .models import CalenderEvent

class CalenderEventForm(forms.ModelForm):
    class Meta:
        model = CalenderEvent
        fields = ['creator_name','event_level','event_name','location','start_date','start_time','description']
        widgets = {
            'creator_name': forms.HiddenInput(
                attrs={'id': 'creator_name', 'required': True, 'placeholder': 'Your Name'}
            ),
            'start_date':forms.HiddenInput(
                attrs={'id': 'start_date', 'required': True, 'placeholder': 'Start Date'},
            ),
            'description':forms.Textarea(
                attrs={'rows':3}
            ),
        }

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Enter Your First Name')
    last_name = forms.CharField(max_length=30, required=True, help_text='Enter Your Last Name')

    class Meta:
        model = User
        fields = ('username','first_name','last_name','password1','password2',)

class LoginForm(AuthenticationForm):
    def confirm_login_allowed(self, user):
        if not user.is_active or not user.is_validated:
            raise forms.ValidationError('There was a problem with your login.', code='invalid_login')

calender/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,JsonResponse
from django.utils import timezone
import json
from .models import CalenderEvent
from .forms import CalenderEventForm
# Create your views here.

@login_required
def index(request):
    #event_id = request.GET['id']
    form = CalenderEventForm()
    return render(request,'calender/index.html',{'form':form})

def newEvent(request):
    #form = CalenderEventForm()
    #return render(request, 'core/signup.html', {'form':form})
    if request.method == "POST":
        form = CalenderEventForm(request.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.creator_name = request.session['firstname']
            event.save()
            return HttpResponse(json.dumps({'status':'ok'}))
        else:
            return HttpResponse(json.dumps({'status':'failed'}))
    else:
        return HttpResponse("Invalid Request")

@login_required
def events_for_month(request):
    if 'month' in request.GET and request.GET['month'] != '':
        date = request.GET['month']
        q = CalenderEvent.objects.filter(start_date__contains=date).values().order_by('start_date')
        response = list(q)
        #return HttpResponse(json.dumps(response))
        return JsonResponse(response,safe=False)
    else:
        return HttpResponse("Specify date as GET parameter baseurl?date=")

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import SignUpForm,LoginForm
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def dash(request):
	return render(request, 'core/dash.html')

def comingsoon(request):
	return render(request,'comingsoon.html')

def signup(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)
		if form.is_valid():
			user = form.save(commit=False)
			user.is_active = False
			user.email = form.cleaned_data.get('password1') + "@tvr.com"
			user.save()
			return render(request,'core/notactive.html')
	else:
		form = SignUpForm()
	return render(request, 'core/signup.html', {'form':form})
	
def authorize(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username=username, password=password)
		if user is not None:  #to check whether user is available or not?
			# the password verified for the user
			if user.is_active:
				login(request, user)
				request.session['firstname'] = user.first_name
				request.session['username'] = user.username
				messages.success(request, "Welcome "+user.first_name)
				if 'next' in request.GET:
				    return redirect(request.GET['next'])
				return redirect('dash')
				#return render(request, "core/dash.html")
			else:
				# Inactive account
				form = LoginForm(request.POST)
				messages.warning(request, "Your account is not activated")
				return render(request,'core/notactive.html')
		else:
    		# the authentication system was unable to verify the username and password
			form = LoginForm(request.POST)
			messages.error(request, "The username and password were incorrect.")
	else:
		form = LoginForm()
	if 'username' in request.session:
	    messages.error(request, "Are you a human?")
	    return redirect('dash')
	return render(request,'core/login.html', {'form':form})

landingpage/views.py
from django.shortcuts import render,redirect
#from django.http import HttpResponse

def index(request):
    if 'username' in request.session:
        return redirect('dash')
    return render(request, 'landing_page/index.html')

calender/templates/calender/index.html
{% extends 'layout.html' %}
{% load widget_tweaks %}
{% block title %}
Calender-Monthly View
{%  endblock %}

{% block main %}
<div class="col-sm-12">
  <div class="row">
      <h2 id="calender_title">Calender</h2>
  </div>

  <div class="row" style="text-align: center;">
    <table class="table">
      <thead id="calender_head"></thead>
      <tbody id="calender_body" style="text-align:middle;"></tbody>
    </table>
  </div>

  <div class="row">
    <ul class="pager">
       <li class="previous"><a href="#">Previous</a></li>
       <li class=""></li>
       <li class="next"><a href="#">Next</a></li>
     </ul>
  </div>
</div>
<!-- Modal -->
    <div id="addnewModal" class="modal fade" role="dialog" style="overflow-y:scroll;">
      <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content">
            <form class="form" action="" method="post" id="addnewEventForm">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" id="addnewModal_title"></h4>
              </div>
              <div class="modal-body">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                  {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                  {% if field.errors %}
                  <div class="form-group has-error">
                  {% else %}
                  <div class="form-group">
                  {% endif %}
                    <label for="{{ field.id_for_labels }}">{{ field.label }}</label>
                    {{ field|add_class:'form-control' }}
                    {% for error in field.errors %}
                      <span class="help-block">{{error}}</span>
                      <script>toastr["error"]("{{error}}", "Error")</script>
                    {% endfor %}
                  </div>
                {% endfor %}
              </div>
              <div class="modal-footer">
                <button type="submit" class="btn btn-success">Add</button>
              </div>
            </form>
        </div>
      </div>
    </div>
    <!-- End of Modal -->

<script type="text/javascript">

  var monthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
  var dayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
  var monthlyEvents = "";
  var daywiseTotalEvents = []
  var lastaddmonth = ""

  function render_calender(year,cmonth) {
    cmonth = parseInt(cmonth) - 1
    adjheaders(); // Adjust the headers

    var innerhtml = "<tr>" // Padding for the last month

    var totalFeb = ""; // Stores Total days in FEB
    if ((year % 100 !== 0) && (year % 4 === 0) || (year % 400 === 0))
      totalFeb = 29;
    else
      totalFeb = 28;
    var totalDays = ["31", "" + totalFeb + "", "31", "30", "31", "30", "31", "31", "30", "31", "30", "31"];

    var adjmonth = parseInt(cmonth) + 1; // Adjusts the current month by 1
    var firstMonthDay = new Date(adjmonth + ' 1 ,' + year); // First Day of Month
    var firstWeekDay = firstMonthDay.getDay(); // Week day equiv of First Day of Month

    var temp = parseInt(firstWeekDay);
    var lastmonthtotal = totalDays[(cmonth-1) < 0?(cmonth-1 + 12 ):(cmonth-1)]

    // Adjust padding for the previous month
    while(temp-- > 0)
      innerhtml += "<td></td>"

    var i = firstWeekDay
    var currentMonthTotal = totalDays[cmonth]
    var day = 1

    while (day <= currentMonthTotal) {
      if(i % 7 == 0 )
        innerhtml += "</tr><tr>"
      innerhtml += "<td onclick=\"showEvents("+day+","+cmonth+","+year+")\"><h4>"+day+"</h4>"
      if(!isNaN(daywiseTotalEvents[day]))
        innerhtml += "<span class=\"badge\">"+daywiseTotalEvents[day]+"</span>"
      innerhtml += "</td>"
      i++;
      day++;
    }
    innerhtml += "</tr>"

    document.getElementById('calender_body').innerHTML = innerhtml;
    document.getElementById('calender_title').innerHTML = "Calender: "+monthNames[cmonth]+", "+year

  }

  function hide_modal(){
    document.getElementById('modal_body').innerHTML = ""
    $('#message').modal('hide');
  }
  function striphtmltags(variable) {
    variable = variable.split("<").join("&lt;");
    variable = variable.split(">").join("&gt;");
    return variable;
  }

  function render_month(year,month) {
    if(month < 10)
      month = "0"+month
    $('#message').modal();
    document.getElementById('modal_head').innerHTML = "<h3>Loading: "+ monthNames[parseInt(month)-1] +", "+year
    document.getElementById('modal_body').innerHTML = loaderHTML
    var xh = new XMLHttpRequest();
    xh.onreadystatechange = function() {
      if (this.readyState == 4 && this.status == 200) {
        monthlyEvents = JSON.parse(xh.responseText);
        distributeEvents();
        render_calender(year,month);
        setTimeout(hide_modal,1000);
      }
      else if(this.status == 500){
        document.getElementById('modal_body').innerHTML = "Server Error, Take a Screen-Shot & Ping Joydeep"
      }
    };
    xh.open("GET","/calender/getEventsByMonth?month="+year+"-"+month)
    xh.send()
  }

  function distributeEvents(){
    for(var i = 0; i < monthlyEvents.length;i++){
      date = parseInt(monthlyEvents[i].start_date.split("-")[2])
      if(isNaN(daywiseTotalEvents[date]))
        daywiseTotalEvents[date] = 0
      daywiseTotalEvents[date] += 1
    }
  }

  function showEvents(day,month,year) {
    $('#message').modal();
    if(++month < 10)
      month = "0"+month
    if(day < 10)
      day = "0"+day
    document.getElementById('modal_head').innerHTML = "<h3>Events For: "+day+", "+monthNames[parseInt(month)-1]+"</h3>"
    var innerhtml = "<div class=\"panel-group\" id=\"EventsAccordion\">"
    var incheck = 0
    for(var i = 0; i < monthlyEvents.length;i++){
      temp_day = parseInt(monthlyEvents[i].start_date.split("-")[2])
      if(parseInt(temp_day) == parseInt(day)){
        incheck++;
        innerhtml += "<div class=\"panel panel-default\">"
        innerhtml +=  "<a class=\"list-group-item\" data-toggle=\"collapse\" data-parent=\"#EventsAccordion\" href=\"#collapse"+i+"\">"
        //innerhtml +=    "<h4 class=\"panel-title\">"
        innerhtml +=       ""+striphtmltags(monthlyEvents[i].event_name)+""
        innerhtml +=       "<span class=\"badge\">"+striphtmltags(monthlyEvents[i].event_level)+"</span>"
        //innerhtml +=    "</h4>"
        innerhtml +=  "</a>"
        innerhtml +=  "<div id=\"collapse"+i+"\" class=\"panel-collapse collapse"+((incheck == 1)?" in":"")+"\">"
        innerhtml +=    "<div class=\"panel-body\">"
        innerhtml +=    "<p><b>Time: </b>"+striphtmltags(monthlyEvents[i].start_time)+"</p>"
        innerhtml +=    "<p><b>At: </b>"+striphtmltags(monthlyEvents[i].location)+"</p>"
        innerhtml +=    "<p><b>Description: </b>"+striphtmltags(monthlyEvents[i].description)+"</p>"
        innerhtml +=    "<p><b>Updated by: </b><span class=\"label label-info\">"+monthlyEvents[i].creator_name+"</span></p>"
        innerhtml +=    "<div class=\"modal-footer\"><button class=\"btn btn-warning\" onclick=\"editEvent('"+monthlyEvents[i].event_id+"')\">Edit</button></div>"
        innerhtml +=    "</div>"
        innerhtml +=  "</div>"
        innerhtml +="</div>"
      }
    }
    if(incheck == 0)
      innerhtml += "<p>No Events for today, create some new</p>"
    innerhtml += "</div>"
    document.getElementById('modal_body').innerHTML = innerhtml
    innerhtml = "<button class=\"btn btn-success\" onclick=\"addEvent('"+day+"','"+month+"','"+year+"')\">Add New Event</button>"
    document.getElementById('modal_footer').innerHTML = innerhtml;
  }
  function addEvent(day,month,year) {
    //toastr["error"]("Thanks for your interest, but this feature is cumming soon- Joydeep", "Ouch!")
    document.getElementById('modal_body').innerHTML = ""
    document.getElementById('modal_footer').innerHTML = ""
    hide_modal();
    document.getElementById('addnewModal_title').innerHTML = "New Event On: "+day+", "+monthNames[parseInt(month)- 1]
    document.getElementById('creator_name').value = "{{ request.session.firstname }}";
    document.getElementById('start_date').value = year + "-" + month + "-" + day
    lastaddmonth = year + "-" + month + "-" + day
    //console.log(document.getElementById('creator_name').value);
    $('#addnewModal').modal('toggle');
  }
  function editEvent(eventID){
    toastr["error"]("Thanks for your interest, but this feature is cumming soon- Joydeep", "Ouch!")
  }
  function adjheaders() {
    var innerhtml = "";
    if ($(window).width() < 650)
        innerhtml += "<th>Sun</th> <th>Mon</th> <th>Tues</th> <th>Wed</th> <th>Thur</th> <th>Fri</th> <th>Sat</th>";
     else
        innerhtml += "<th>Sunday</th><th>Monday</th><th>Tuesday</th><th>Wednesday</th><th>Thursday</th><th>Friday</th><th>Saturday</th>";
    document.getElementById('calender_head').innerHTML = innerhtml;
  }
  function rerender(){
    //console.log("rerender callled");
    daywiseTotalEvents = []
    render_month(parseInt(lastaddmonth.split("-")[0]),parseInt(lastaddmonth.split("-")[1]))
  }
  $(window).resize(function() {
    adjheaders();
  });
  document.onreadystatechange = function () {
    if (document.readyState === "complete") {
      render_month(2017,9)
    }
  }

  $('#addnewEventForm').on('submit', function(event){
    event.preventDefault();
    console.log("form submitted!")  // sanity check
    post_eventForm();
  });
  function post_eventForm() {
    //console.log("Ajax Post is working!") // sanity check
    //console.log($('#id_event_name').val())
    toastr["info"]("Till server processes your event", "Wait")
    $.ajax({
        url : "{% url 'add_new_event' %}", // the endpoint
        type : "POST", // http method
        data:  $('#addnewEventForm').serialize(),

        // handle a successful response
        success : function(json) {
          toastr["success"]("Your event added", "Voila")
           $('#addnewEventForm')[0].reset();
           $('#addnewModal').modal('toggle');
           rerender();
        },

        // handle a non-successful response
        error : function(xhr,errmsg,err) {
          toastr["error"]("Your event was not added", "Error")
        }
    });
  };

/* Ajax Form Submission with csfr token validation */
  $(function() {
    // This function gets cookie with a given name
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');

    /*
    The functions below will create a header with csrftoken
    */

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    function sameOrigin(url) {
        // test that a given url is a same-origin URL
        // url could be relative or scheme relative or absolute
        var host = document.location.host; // host + port
        var protocol = document.location.protocol;
        var sr_origin = '//' + host;
        var origin = protocol + sr_origin;
        // Allow absolute or scheme relative URLs to same origin
        return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
            (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
            // or any other URL that isn't scheme relative or absolute i.e relative.
            !(/^(\/\/|http:|https:).*/.test(url));
    }

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && sameOrigin(settings.url)) {
                // Send the token to same-origin, relative URLs only.
                // Send the token only if the method warrants CSRF protection
                // Using the CSRFToken value acquired earlier
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

  });
</script>
{% endblock %}

core/templates/comingsoon.html
{% extends "layout.html" %}

{% block main %}
<div class="row">
  <div class="col-sm-12">
    <div class="jumbotron">
      <legend>Aw, Snap :(</legend>
      <h3>Thanks for your interest in Techventure website</h3>
      <h4>But we haven't developed this feature yet</h4>
      <h4>We are humans, we are not EMINEM please bear with :)</h4>
      <h4>Till then, listen Rap God</h4>
    </div>
  </div>
</div>
{% endblock %}

core/templates/core/dash.html
{% extends "layout.html" %}

{% block main %}
  <h2>Welcome, {{request.session.firstname}}</h2>
  <hr>
  <p>Actually this is a boring dashboard, but you can verify that you are logged in.</p>
  <p>Grab some popcorn, These features are coming soon</p>
  <ul>
    <li>
      <a href="/calender">Calender / Scheduler</a> [Now UNDER development]
      <br> Try out this feature as your feedback matters :) - Joydeep
      <br>
      <hr>
    </li>
    <li>
      Quora style Q&A
    </li>
    <li>
      Medium style blog
    </li>
    <li>
      Some More Functionality
    </li>
  </ul>

{% endblock %}

core/templates/core/login.html
{% extends 'layout.html' %}
{% load widget_tweaks %}
{% block title %}Login{% endblock %}
{% block main %}
<div class="col-sm-4"></div>
<div class="col-sm-4">
  <h2>Login</h2>
  <hr>
  <form class="" method="post">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
      {{ hidden }}
    {% endfor %}
    {% for field in form.visible_fields %}
      {% if field.errors %}
        <div class="form-group has-error">
      {% else %}
        <div class="form-group">
      {% endif %}
        <label for="{{ field.id_for_labels }}">{{ field.label }}</label>
        {{ field|add_class:'form-control' }}
        {% for error in field.errors %}
          <span class="help-block">{{error}}</span>
        {% endfor %}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-success">Login</button>
  </form>
  <br><p>Not a User? <a href="{% url 'signup' %}">Register Here</a></p>
  </div>
<div class="col-sm-4"></div>
{% endblock %}

core/templates/core/notactive.html
{% extends "layout.html" %}

{% block main %}
  <h2>Access Denied</h2>
  <hr>
  <p>Thank you for your interest in Techventure</p>
  <p>Your account is not activated. Please fill up the registration form available at XEROX Centre</p>
  <p>You can ask Joydeep to activate your user account</p>


{% endblock %}

core/templates/core/signup.html
{% extends 'layout.html' %}
{% load widget_tweaks %}
{% block title %}Register{% endblock %}
{% block main %}
<div class="col-sm-6"></div>
<div class="col-sm-6">
    <h2>Signup</h2>
    <form class="" method="post">
      {% csrf_token %}
      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}
      {% for field in form.visible_fields %}
        {% if field.errors %}
        <div class="form-group has-error">
        {% else %}
        <div class="form-group">
        {% endif %}
          <label for="{{ field.id_for_labels }}">{{ field.label }}</label>
          {{ field|add_class:'form-control' }}
          {% for error in field.errors %}
            <span class="help-block">{{error}}</span>
            <script>toastr["error"]("{{error}}", "Error")</script>
          {% endfor %}
        </div>
      {% endfor %}
      <button type="submit" class="btn btn-success">Sign Up</button>
    </form>
</div>
{% endblock %}

core/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta -->
  <meta charset="utf-8" />
  <meta content="initial-scale=1, width=device-width" name="viewport" />
  <!-- documentation at http://getbootstrap.com/, alternative themes at https://www.bootstrapcdn.com/bootswatch/ -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/yeti/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="/static/loader/loader.css" rel="stylesheet"/>
  <link rel="stylesheet" href="/static/toastr/toastr.css" rel="stylesheet"/>
  <script src="/static/toastr/toastr.min.js"></script>
  <title>{% block title %}{% endblock %} | GCETTS Techventure</title>
  {% block head %} {% endblock %}
  <script>
      toastr.options = {
        "closeButton": true,
        "debug": false,
        "newestOnTop": true,
        "progressBar": true,
        "positionClass": "toast-bottom-left",
        "preventDuplicates": false,
        "showDuration": "300",
        "hideDuration": "1000",
        "timeOut": "5000",
        "extendedTimeOut": "1000",
        "showEasing": "swing",
        "hideEasing": "swing",
        "showMethod": "slideDown",
        "hideMethod": "slideUp"
      }
  </script>
  <script>
    var loaderHTML = "<div class=\"spinner\"><div class=\"bounce1\"></div><div class=\"bounce2\"></div><div class=\"bounce3\"></div></div>"
  </script>

</head>

<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button aria-expanded="false" class="navbar-toggle collapsed" data-target="#navbar" data-toggle="collapse" type="button">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
        <a class="navbar-brand" href="{% url 'dash' %}">Techventure</a>
      </div>
      <div class="collapse navbar-collapse" id="navbar">
        {% if request.session.username %}
        <ul class="nav navbar-nav">
          <li><a href="{% url 'cusoon' %}">Poll</a></li>
          <li><a href="{% url 'calender_index' %}">Calender</a></li>
          <li><a href="{% url 'cusoon' %}">Blog</a></li>
          <li><a href="{% url 'cusoon' %}">QA</a></li>
        </ul>
        {% endif %}
        <ul class="nav navbar-nav navbar-right">
          {% if request.session.username %}
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <span class="glyphicon glyphicon-menu-down"></span> {{ request.session.firstname }}
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="{% url 'cusoon' %} "><span class="glyphicon glyphicon-wrench"></span> Change Password</a></li>
              <li><a href="{% url 'cusoon' %}"><span class="glyphicon glyphicon-plus"></span> Area 51</a></li>
              <li class="divider"></li>
              <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
            </ul>
          </li>
          {% else %}
            <li><a href="{% url 'login' %}">Login</a></li>
            <li><a href="{% url 'signup' %}">Create Account</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% if messages %}
      {% for message in messages %}
        <script>toastr["{{ message.tags}}"]("", "{{  message }}")</script>
      {% endfor %}
    {% endif %}
    <main>
      {% block main %}
      {% endblock %}
    </main>
    <!-- Modal -->
    <div id="message" class="modal fade" role="dialog">
      <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title" id="modal_head">Techventure</h4>
          </div>
          <div class="modal-body" id="modal_body">
            <p>GCETTS</p>
          </div>
          <div class="modal-footer" id="modal_footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    <!-- End of Modal -->
  </div>

</body>

</html>